### ISSUE TITLE
system song doesn't update

### ISSUE THREAD

**Issue by mcfalld** [Casterlabs/Casterlabs#16]
when I use the system for music, the song doesn't update unless I click on the volume icon and have Windows display to me the current song. Windows 11

**Comment by e3ndr** [comment]
Sounds like a Windows bug, what program are you using for playback?

**Comment by mcfalld** [comment]
music is playing in amazon music app.

**Comment by mcfalld** [comment]
suppose i could try amazon music in a browser not sure if that would help.

**Comment by mcfalld** [comment]
> suppose i could try amazon music in a browser not sure if that would help.

well amazon music doesn't support my browser. 

![image](https://github.com/Casterlabs/Casterlabs/assets/32588824/67ae8550-334f-4140-9e03-637726675c40)

**Comment by mcfalld** [comment]
hmm well my apologies for the confusion. it seems like it doesn't update if im looking at the settings page but if im in the dashboard it does update. so this can probably be closed.

**Comment by e3ndr** [comment]
> hmm well my apologies for the confusion. it seems like it doesn't update if im looking at the settings page but if im in the dashboard it does update. so this can probably be closed.

that's weird, i'll figure out why that is. thanks for reporting :^)
